name: robust_http
description: Robust http client package
version: 1.0.0
homepage:

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  connectivity_plus: ^4.0.1
  logger: ^1.3.0
  dio: ^5.1.2
  http: ^1.0.0
  enum_to_string: ^2.0.1
  singleton: ^0.0.3-nullsafety
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
