name: robust_http
description: Robust http client package
version: 1.0.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  connectivity_plus: ^2.3.0
  logger: ^1.0.0
  dio: ^4.0.6
  http: ^0.13.4
  enum_to_string: ^2.0.1
  singleton: ^0.0.3-nullsafety
  internet_connection_checker: ^0.0.1+3
  mime_type: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
