name: robust_http
description: Robust http client package
version: 1.0.0
homepage:

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  connectivity_plus: ^6.1.3
  logger: ^2.5.0
  dio: ^5.8.0+1
  http: ^1.3.0
  enum_to_string: ^2.2.0
  singleton: ^0.0.3-nullsafety
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
